config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  root "texts#index"
  resources :texts, only: [:index, :show] do
    resource :read_progresses, only: [:create, :destroy]
  end
  resources :movies, only: :index do
    resource :watch_progresses, only: [:create, :destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :watch_progresses, dependent: :destroy

  with_options presence: true do
    validates :genre
    validates :title
    validates :url
  end

  enum genre: {
    invisible: 0, # 非表示
    basic: 1,
    git: 2,
    ruby: 3,
    rails: 4,
    php: 5
  }

  RAILS_GENRE_LIST = %w[basic git ruby rails].freeze

  def watch_by?(user)
    watch_progresses.any? { |watch_progress| watch_progress.user_id == user.id }
  end
end

app/models/read_progress.rb
class ReadProgress < ApplicationRecord
  belongs_to :user
  belongs_to :text
  validates :user_id, uniqueness: { scope: :text_id }
end

app/models/text.rb
class Text < ApplicationRecord
  has_many :read_progresses, dependent: :destroy

  with_options presence: true do
    validates :genre
    validates :title
    validates :content
  end

  enum genre: {
    invisible: 0, # 非表示
    basic: 1,
    git: 2,
    ruby: 3,
    rails: 4,
    php: 5
  }

  RAILS_GENRE_LIST = %w[basic git ruby rails].freeze
  PHP_GENRE_LIST = %w[php].freeze

  def self.genre_list(genre)
    if genre == "php"
      where(genre: Text::PHP_GENRE_LIST)
    else
      where(genre: Text::RAILS_GENRE_LIST)
    end
  end

  def read_by?(user)
    read_progresses.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :read_progresses, dependent: :destroy
  has_many :watch_progresses, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: "test@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/watch_progress.rb
class WatchProgress < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, uniqueness: {
    scope: :movie_id
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  PER_PAGE = 12

  def index
    @movies = if params[:genre]
                Movie.where(genre: "php").includes(:watch_progresses).page(params[:page]).per(PER_PAGE)
              else
                Movie.where(genre: Movie::RAILS_GENRE_LIST).includes(:watch_progresses).page(params[:page]).per(PER_PAGE)
              end
  end
end

app/controllers/read_progresses_controller.rb
class ReadProgressesController < ApplicationController
  def create
    @text = Text.find(params[:text_id])
    current_user.read_progresses.create!(text_id: @text.id)
  end

  def destroy
    @text = Text.find(params[:text_id])
    current_user.read_progresses.find_by(text_id: @text.id).destroy!
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def index
    @texts = Text.genre_list(params[:genre])
  end

  def show
    @text = Text.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def guest_sign_in
      sign_in User.guest
      redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
    end
  end
end

app/controllers/watch_progresses_controller.rb
class WatchProgressesController < ApplicationController
  def create
    @movie = Movie.find(params[:movie_id])
    current_user.watch_progresses.create!(movie_id: @movie.id)
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    current_user.watch_progresses.find_by(movie_id: @movie.id).destroy!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def max_width
    if controller_name == "texts" && action_name == "show"
      "mw-md"
    elsif devise_controller?
      "mw-sm"
    else
      "mw-xl"
    end
  end

  def page_title
    if params[:genre] == "php"
      "PHP"
    else
      "Ruby/Rails"
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(render_options)
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end

  private

  def render_options
    {
      filter_html: false, # htmlを無効化
      hard_wrap: true, # 改行を br 要素に変換
      link_attributes: { target: "_blank", rel: "noopener" } # リンクの設定
    }
  end

  def extensions
    {
      autolink: true, # http https ftpで始まる文字列を自動リンク
      fenced_code_blocks: true, # コードブロックを解析
      no_intra_emphasis: true, # 単語内の強調を解析しない
      tables: true, # 	テーブルを解析
      space_after_headers: true, # ヘッダーの先頭のハッシュとハッシュ名の間にスペースを要求
      hard_wrap: true, # 改行を br 要素に変換
      xhtml: true, # xhtml のタグを出力する(Render::XHTMLでは常に有効)
      lax_html_blocks: true # 複数行のコードの前後に空行が不要
      # strikethrough: true, # 取り消し線(~)を解析する
    }
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def embed_youtube(url)
    tag.iframe(
      width: 304,
      height: 166,
      src: url,
      frameborder: 0,
      allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture",
      allowfullscreen: true
    )
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("yanbaru_expert_logo.png") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav mr-auto ml-3">
      <li class= "nav-item active dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Ruby</a>
        <div class="dropdown-menu">
          <%= link_to "Ruby/Railsテキスト教材", texts_path, class: "dropdown-item" %>
          <%= link_to "Ruby/Rails動画教材", movies_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class= "nav-item active dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">PHP</a>
        <div class="dropdown-menu">
          <%= link_to "PHPテキスト教材", texts_path(genre: "php"), class: "dropdown-item" %>
          <%= link_to "PHP動画教材", movies_path(genre: "php"), class: "dropdown-item" %>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class= "nav-item">
          <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-item nav-link active" %>
        </li>
        <li class= "nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, class: "nav-item nav-link active", method: :delete, data: { confirm: "ログアウトしますか？" } %>
        </li>
      <% else %>
        <li class= "nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-item nav-link active" %>
        </li>
        <li class= "nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active" %>
        </li>
        <li class= "nav-item">
          <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-item nav-link active" %>
        </li>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>チーム開発 やんばるエキスパート教材クローン</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= render "layouts/flash" %>
      <%# max_width メソッドは `application_helper.rb` に記載 %>
      <div class="base-container <%= max_width %>">
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/movies/_movie.html.erb
<div class="col-12 col-md-6 col-lg-4">
  <div class="card content-card border-dark mb-3">
    <div class="card-header p-0">
      <div class="embed-responsive embed-responsive-16by9">
        <%= embed_youtube(movie.url) %>
      </div>
    </div>
    <div class="card-body text-dark">
      <p id="movie-<%= movie.id %>">      
        <object>
          <% if movie.watch_by?(current_user) %>
            <%= render "watch", movie: movie %>
          <% else %>
            <%= render "unwatch", movie: movie %>
          <% end %>
        </object>
      </p>
      <p class="card-text mt-3">Lv.<%= @movies.offset_value + 1 + movie_counter %>：<%= movie.title %></p>
    </div>
  </div>
</div>

app/views/movies/_unwatch.html.erb
<%= link_to "視聴済みにする", movie_watch_progresses_path(movie), method: :post, remote: true, class: "btn btn-secondary btn-block" %>

app/views/movies/_watch.html.erb
<%= link_to "視聴済みを解除", movie_watch_progresses_path(movie), method: :delete, remote: true, class: "btn btn-primary btn-block" %>

app/views/movies/index.html.erb
<div class="contents-title text-center">
  <% if params[:genre] %>
    <h1>PHP 動画</h1>
  <% else %>
    <h1>Ruby/Rails 動画</h1>
  <% end%>
</div>
<div class="row">
  <%= render @movies %>
</div>
<%= paginate @movies %>

app/views/read_progresses/create.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/read", text: @text) %>'

app/views/read_progresses/destroy.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/unread", text: @text) %>'

app/views/texts/_read.html.erb
<%= link_to "読破済みを解除", text_read_progresses_path(text), method: :delete, remote: true, class: "btn btn-primary btn-block" %>

app/views/texts/_text.html.erb
<div class="col-12 col-md-6 col-lg-4">
  <div class="card content-card border-dark mb-3">
    <%= link_to text_path(text) do %>
      <div class="card-header p-0">
        <img loading="lazy" alt="<%= text.title %> "class="img-fluid" src="https://d5izmuz0mcjzz.cloudfront.net/texts/no_image.jpg">
      </div>
      <div class="card-body text-dark">
        <p id="text-<%= text.id %>">
          <object>
            <% if text.read_by?(current_user) %>
              <%= render "read", text: text %>
            <% else %>
              <%= render "unread", text: text %>
            <% end %>
          </object>
        </P>
        <p class="card-text mt-3"><%= text.title %></p>
        <p>【<%= text.genre_i18n %>】</p>
      </div>
    <% end %>
  </div>
</div>

app/views/texts/_unread.html.erb
<%= link_to "読破済みにする", text_read_progresses_path(text), method: :post, remote: true, class: "btn btn-secondary btn-block" %>

app/views/texts/index.html.erb
<h1 class="text-center mt-2 mb-4">
  <%= page_title%><br class="d-sm-none">
  テキスト教材
</h1>
<div class="row">
  <%= render @texts %>
</div>

app/views/texts/show.html.erb
<h1 class="text-center my-4" ><%= @text.title %></h1>
<div class="markdown">
  <%= markdown(@text.content) %>
</div>

app/views/watch_progresses/create.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/watch", movie: @movie) %>'

app/views/watch_progresses/destroy.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/unwatch", movie: @movie) %>'